spring:
  profiles:
    active:
    - dev 
---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.yds.springcloud.entities        # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept 
  datasource:
    type: com.zaxxer.hikari.HikariDataSource                # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://192.168.1.132:3306/cloudDB01          # 数据库名称
    username: root
    password: 123456
    hikari:
      minimum-idle: 5                                       # 数据库连接池的最小维持连接数
      maximum-pool-size: 5                                  # 最大连接数
      connection-timeout: 30000                             # 等待连接获取的超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/      
  instance:
    instance-id: microservicecloud-config-dept8001  #界面上显示的名称
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
info: #注册服务的说明信息，可以自定义
  app.name: microservicecloud-config-dept
  company.name: www.xxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.yds.springcloud.entities        # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept   
  datasource:
    type: com.zaxxer.hikari.HikariDataSource                # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://192.168.1.132:3306/cloudDB03          # 数据库名称
    username: root
    password: 123456
    hikari:
      minimum-idle: 5                                       # 数据库连接池的最小维持连接数
      maximum-pool-size: 5                                  # 最大连接数
      connection-timeout: 30000                             # 等待连接获取的超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/      
  instance:
    instance-id: microservicecloud-config-dept8001  #界面上显示的名称
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
info: #注册服务的说明信息，可以自定义
  app.name: microservicecloud-config-dept
  company.name: www.xxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$